server:
  port: 9090

spring:
  application:
    name: capgemini-demo
  # 解决 SpringFox 与 SpringBoot 2.6.x 不兼容的问题
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  # liquibase 配置
  liquibase:
    change-log: classpath:/db/changelog-master.xml
  # 数据源配置
  datasource:
    druid: # Druid 【连接池】相关的全局配置
      initial-size: 5 # 初始连接数
      min-idle: 10 # 最小连接池数量
      max-active: 20 # 最大连接池数量
      max-wait: 600000 # 配置获取连接等待超时的时间，单位：毫秒
      time-between-eviction-runs-millis: 60000 # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位：毫秒
      min-evictable-idle-time-millis: 300000 # 配置一个连接在池中最小生存的时间，单位：毫秒
      max-evictable-idle-time-millis: 900000 # 配置一个连接在池中最大生存的时间，单位：毫秒
      validation-query: SELECT 1 FROM DUAL # 配置检测连接是否有效
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false

    # MySQL配置
    url: jdbc:mysql://localhost:3306/capgemini_delivery_demo?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

# MyBatis Plus 的配置
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #控制台级别日志
  global-config:
    db-config:
      logic-delete-value: 1 # 逻辑已删除值
      logic-not-delete-value: 0 # 逻辑未删除值
      id-type: auto


capgemini-demo:
  swagger:
    title: capgemini-demo-documentation
    description: 提供整个系统接口
    version: ${capgemini-demo.info.version}
    enabled: true
  info:
    version: 1.0.0

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
    show-extensions: true
  api-docs:
    path: /v3/api-docs
    enabled: true
  group-configs:
    - group: 'capgemini-demo-documentation'
      paths-to-match: '/**'
      packages-to-scan: com.capgemini.business.controller
  default-flat-param-object: false

knife4j:
  enable: true
